# NUMPY 

Numpy is an external python library or tool which is known as numerical python


##### TO USE NUMPY


In [23]:
import numpy as np

### NUMPY DATA STRUCTURE


* ARRAY --> It is a collection of similar types of data seperated by space
* E.g:  [number_1 number_2 number_3 number_4] --> we cannot create an array directly
* nan --> (NOT A NUMBER) --> Empty data in numpy

### dtype

dtype --> data type


* PYTHON DATATYPES
1. INT --> int64,int32,int16,int8
2. FLOAT --> float64,float32,float16,float8


* NUMPY DATATYPES

1. INT --> np.int64, np.int32, np.int16, np.int8
2. FLOAT --> np.float64, np.float32, np.float16, np.float8

### ARRAY CREATION METHODS

* We can create both 1D and 2D arrays in numpy.
* we can create 2D array using array() with the help of nested list where each list inside the nested list will represent rows of 2D array

#### array()


1. It is a numpy method to create array
2. It creates and returns an array as per defined data
3. Syntax --> np.array(caoolection of data)

In [24]:
a = np.array([2,3,4,5])
print(a)

[2 3 4 5]


In [25]:
import numpy as np
r = np.array([[1, 2, 3], [4, 5, 6]])
print(r)

[[1 2 3]
 [4 5 6]]


#### arange()

1. syntax --> np.arange(start,stop,step)
2. returns an array as per defined range 

In [26]:
a = np.arange(5)
print(a)

[0 1 2 3 4]


In [27]:
a = np.arange(1,5,)
print(a)

[1 2 3 4]


#### ones()

1. It creates an array of "one"
2. syntax --> np.ones(size) --> bydefault dtype is float

In [28]:
print(np.ones(5))

[1. 1. 1. 1. 1.]


In [29]:
print(np.ones(10,dtype = np.int64))

[1 1 1 1 1 1 1 1 1 1]


#### ones_like()

1. This function returns a new array with the same shape & data type as given array, but fills it completely with "1".
2. syntax --> np.ones_like(a) --> a is refrence array

In [30]:
a = np.array([[2,4,5,6],[7,8,9,20]])
print(np.ones_like(a))

[[1 1 1 1]
 [1 1 1 1]]


#### zeros()

1. It creates an array of "zeros"
2. syntax --> np.zeros(size) --> default dtype is float

In [31]:
print(np.zeros(10))

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


In [32]:
print(np.zeros(10,dtype=np.int32))

[0 0 0 0 0 0 0 0 0 0]


#### zeros_like()

1. This function returns a new array with the same shape & data type as given array, but fills it completely with "0".
2. syntax --> np.zeros_like(a) --> a is refrence array

In [33]:
a = np.array([[2,4,5,6,7,8],[1,2,3,4,5,6]])
print(np.zeros_like(a))

[[0 0 0 0 0 0]
 [0 0 0 0 0 0]]


#### full()

1. It is used to create an array of any desired data.
2. syntax --> np.full(size,value)

In [34]:
print(np.full(5,"RISHU"))

['RISHU' 'RISHU' 'RISHU' 'RISHU' 'RISHU']


In [35]:
print(np.full(5,5))

[5 5 5 5 5]


#### full_like()

1. This function returns a new array with the same shape & data type as given array, but fills it completely with a specified value that you choose.
2. syntax --> np.full_like(a,fill_value) --> a is refrence array

In [36]:
a = np.array([[10,20,30,40],[100,200,300,400]])
print(np.full_like(a,18))

[[18 18 18 18]
 [18 18 18 18]]


#### linspace()

1. This function generates an array of evenly spaced numbers over a specified interval.
2. syntax --> np.linspace(start,stop,num = 50) --> num is basically the number of elements(by default 50)

In [37]:
print(np.linspace(1,10))

[ 1.          1.18367347  1.36734694  1.55102041  1.73469388  1.91836735
  2.10204082  2.28571429  2.46938776  2.65306122  2.83673469  3.02040816
  3.20408163  3.3877551   3.57142857  3.75510204  3.93877551  4.12244898
  4.30612245  4.48979592  4.67346939  4.85714286  5.04081633  5.2244898
  5.40816327  5.59183673  5.7755102   5.95918367  6.14285714  6.32653061
  6.51020408  6.69387755  6.87755102  7.06122449  7.24489796  7.42857143
  7.6122449   7.79591837  7.97959184  8.16326531  8.34693878  8.53061224
  8.71428571  8.89795918  9.08163265  9.26530612  9.44897959  9.63265306
  9.81632653 10.        ]


In [38]:
print(np.linspace(1,20,4))

[ 1.          7.33333333 13.66666667 20.        ]


In [39]:
print(np.linspace(1,10,5))

[ 1.    3.25  5.5   7.75 10.  ]


#### identity()

1. It generates a square matrix (a 2D array where number of rows and columns are same), with "1" on the main diagonal and zeros elsewhere
2. Syntax --> np.identity(n) --> n is number of rows(and columns)
3. dtype is np.float64 (default)

In [40]:
print(np.identity(5))

[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]


#### eye()

1. This is a more flexible version of identity()
2. While it also puts ones on the main diagonal & zeros elsewhere.
3. It allows us to create non square matrices & lets us shift the diagonal of "1" up or down
4. syntax --> np.eye(M, M = None , K = 0) 
    * N = number of rows
    * M = number of columns (If None, defaults to N, making the matrix square)
    * K = index of diagonal
        * 0 is the main diagonal
        * positive value shifts it up
        * negative value shifts it down

In [41]:
print(np.eye(5))

[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]


In [42]:
print(np.eye(5,4))

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]
 [0. 0. 0. 0.]]


In [43]:
print(np.eye(5,None,2))

[[0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]


In [44]:
print(np.eye(5,None,-1))

[[0. 0. 0. 0. 0.]
 [1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]]


### ATTRIBUTES OF AN ARRAY

#### size

1. It returns the total number of elements in the array
2. It doesn't care about the rows and columns ; it just counts every single element
3. syntax --> array_name.size

In [45]:
a = np.arange(1,100,5)
print(a)

[ 1  6 11 16 21 26 31 36 41 46 51 56 61 66 71 76 81 86 91 96]


In [46]:
print(r)

[[1 2 3]
 [4 5 6]]


In [47]:
print(a.size)
print(r.size)

20
6


#### shape

1. It returns a tuple representing the dimensions of the array.
2. For a 2D array; it will return (rows,columns)
3. For a 1D array; it will return (elements,)
4. syntax --> array_name.shape

In [48]:
print(a.shape)
print(r.shape)

(20,)
(2, 3)


In [49]:
arr = np.array([[2,3,4],[3,4,5]])
print(arr.shape)

(2, 3)


#### dtype

1. It tells about the specific type of data stored in array (Numpy arrays contain same types of elements)
2. syntax --> array_name.dtype

In [50]:
print(a.dtype)
print(r.dtype)

int64
int64


#### ndim

1. ndim stands for NUMBER OF DIMENSIONS 
2. It returns an integer representing the number of axes the array has (1 for list, 2 for matrix/table, 3 for cube)
3. syntax --> array_name.ndim

In [51]:
print(a.ndim)
print(r.ndim)

1
2


In [52]:
print(arr.ndim)

2


#### itemsize

1. It returns the amount of memory (in bytes) that a single element in array takes up
2. Array uses int64 (64 bits) & 8 bits equal 1 byte so each element takes 8 bytes
3. syntax --> array_name.itemsize

In [53]:
print(a.itemsize)
print(r.itemsize)

8
8


#### nbytes

1. It returns the total memory consumed by entire array (in bytes)
2. nbytes = total elements * size of one element 
3. syntax --> array_name.nbytes
4. NOTE : a.nbytes == a.size * a.itemsize

In [54]:
print(a.nbytes)
print(r.nbytes)

160
48


In [55]:
print(a.size * a.itemsize)

160


### ARRAY ACCESSING

In [56]:
a = np.arange(1,100,2)
print(a)
r = np.array([[1,2,3],[4,5,6]])
print(r)

[ 1  3  5  7  9 11 13 15 17 19 21 23 25 27 29 31 33 35 37 39 41 43 45 47
 49 51 53 55 57 59 61 63 65 67 69 71 73 75 77 79 81 83 85 87 89 91 93 95
 97 99]
[[1 2 3]
 [4 5 6]]


#### ACCESSING USING SUBSCRIPT ([])

#### ACCESSING USING SLICING - 1D

syntax --> arrayname[start_index : stop_index : step]

In [57]:
print(a[:45:])

[ 1  3  5  7  9 11 13 15 17 19 21 23 25 27 29 31 33 35 37 39 41 43 45 47
 49 51 53 55 57 59 61 63 65 67 69 71 73 75 77 79 81 83 85 87 89]


In [58]:
print(a[12::2])

[25 29 33 37 41 45 49 53 57 61 65 69 73 77 81 85 89 93 97]


In [59]:
print(a[::])

[ 1  3  5  7  9 11 13 15 17 19 21 23 25 27 29 31 33 35 37 39 41 43 45 47
 49 51 53 55 57 59 61 63 65 67 69 71 73 75 77 79 81 83 85 87 89 91 93 95
 97 99]


In [60]:
print(a[7:25:5])

[15 25 35 45]


##### SINGLE ELEMENT - 1D

syntax --> array_name[index]

In [61]:
print(a[2])

5


##### MULTIPLE ELEMENTS - 1D

syntax --> array_name[[index_1, index_2, index_3]]

In [62]:
print(a[[1,2,3,4,5]])

[ 3  5  7  9 11]


##### SINGLE ELEMENT - 2D

In [63]:
arr = np.array([[1,2,3,10],[4,5,6,20],[7,8,9,30]])
print(arr)

[[ 1  2  3 10]
 [ 4  5  6 20]
 [ 7  8  9 30]]


In [64]:
print(arr[0])

[ 1  2  3 10]


In [65]:
print(arr[1])

[ 4  5  6 20]


In [66]:
print(arr[2])

[ 7  8  9 30]


In [67]:
print(arr[0][0])

1


In [68]:
print(arr[1][2])

6


* --> we can also pass using comma instead of using two square brackets.

In [69]:
print(arr[1,2]) 

6


#### ACCESSING USING SLICING - 2D

In [70]:
print(arr)

[[ 1  2  3 10]
 [ 4  5  6 20]
 [ 7  8  9 30]]


* For accessing multiple elements in a 2D array, always use slicing in either one part(either rows or columns)
* Never use tradational subscript mehtod as it will return corresponding elements

In [71]:
print(arr[(0,1),(2,3)]) # HERE IT RETURNS THE CORRESPONDING ELEMENTS ie arr[0][2] and arr[1][3] which is 3 and 20

[ 3 20]


In [72]:
print(arr[0:2,0:2]) # SLICING USED IN BOTH ROWS AND COLUMNS

[[1 2]
 [4 5]]


In [73]:
print(arr[0:3,(0,1)]) # SLICING USED ONLY IN ROWS

[[1 2]
 [4 5]
 [7 8]]


In [74]:
print(arr[(0,1),0:3]) # SLICING USED ONLY IN COLUMNS

[[1 2 3]
 [4 5 6]]


In [75]:
print(arr[::-1]) #REVERSES THE ARRAY

[[ 7  8  9 30]
 [ 4  5  6 20]
 [ 1  2  3 10]]


In [76]:
print(arr)

[[ 1  2  3 10]
 [ 4  5  6 20]
 [ 7  8  9 30]]


syntax --> arrayname[start_index : stop_index : step]

In [77]:
print(a[:45:])

[ 1  3  5  7  9 11 13 15 17 19 21 23 25 27 29 31 33 35 37 39 41 43 45 47
 49 51 53 55 57 59 61 63 65 67 69 71 73 75 77 79 81 83 85 87 89]


In [78]:
print(a[12::2])

[25 29 33 37 41 45 49 53 57 61 65 69 73 77 81 85 89 93 97]


In [79]:
print(a[::])

[ 1  3  5  7  9 11 13 15 17 19 21 23 25 27 29 31 33 35 37 39 41 43 45 47
 49 51 53 55 57 59 61 63 65 67 69 71 73 75 77 79 81 83 85 87 89 91 93 95
 97 99]


In [80]:
print(a[7:25:5])

[15 25 35 45]


#### BOOLEAN INDEXING

BOOL means either true or false

1. In array we've multiple types of index i.e positive index, negative index and boolean index
2. Indexing in form of true and false is called boolean indexing
3. In array every element has its own boolean index i.e true and false

#### ACCESSING USING BOOLEAN INDEX

1. WE've to provide boolean index of all elements.
2. If index is true then that corresponding element will be accessed
3. If index is false then that corresponding element will not be accessed
4. Syntax --> arrayname[[boolindex1,boolindex2,....]]

In [81]:
arr = np.array([2,3,4,5,6])
print(arr[[True,True,False,False,False]])

[2 3]


In [82]:
print(a)

[ 1  3  5  7  9 11 13 15 17 19 21 23 25 27 29 31 33 35 37 39 41 43 45 47
 49 51 53 55 57 59 61 63 65 67 69 71 73 75 77 79 81 83 85 87 89 91 93 95
 97 99]


In [83]:
print(a>10)

[False False False False False  True  True  True  True  True  True  True
  True  True  True  True  True  True  True  True  True  True  True  True
  True  True  True  True  True  True  True  True  True  True  True  True
  True  True  True  True  True  True  True  True  True  True  True  True
  True  True]


In [84]:
print(a[a>10])

[11 13 15 17 19 21 23 25 27 29 31 33 35 37 39 41 43 45 47 49 51 53 55 57
 59 61 63 65 67 69 71 73 75 77 79 81 83 85 87 89 91 93 95 97 99]


In [85]:
print(a<50)

[ True  True  True  True  True  True  True  True  True  True  True  True
  True  True  True  True  True  True  True  True  True  True  True  True
  True False False False False False False False False False False False
 False False False False False False False False False False False False
 False False]


In [86]:
print(a[a<50])

[ 1  3  5  7  9 11 13 15 17 19 21 23 25 27 29 31 33 35 37 39 41 43 45 47
 49]


##### FOR 2D

In [87]:
arr = np.array([[45,78,85,1,12,87],[12,87,68,45,6,5],[7,8,9, 100,10000,10]])
print(arr)

[[   45    78    85     1    12    87]
 [   12    87    68    45     6     5]
 [    7     8     9   100 10000    10]]


In [88]:
print(arr>47)

[[False  True  True False False  True]
 [False  True  True False False False]
 [False False False  True  True False]]


In [89]:
print(arr[arr>47])

[   78    85    87    87    68   100 10000]


* Here the output is in form of a 1D array, because the shape is unknown and can be of any type

### ARITHIMATIC OPERATIONS IN ARRAYS

#### Single Value Operations

* array + single value ---> this will add every single element of array to a single value

In [90]:
print(a+10)

[ 11  13  15  17  19  21  23  25  27  29  31  33  35  37  39  41  43  45
  47  49  51  53  55  57  59  61  63  65  67  69  71  73  75  77  79  81
  83  85  87  89  91  93  95  97  99 101 103 105 107 109]


In [91]:
print(a-20)

[-19 -17 -15 -13 -11  -9  -7  -5  -3  -1   1   3   5   7   9  11  13  15
  17  19  21  23  25  27  29  31  33  35  37  39  41  43  45  47  49  51
  53  55  57  59  61  63  65  67  69  71  73  75  77  79]


In [92]:
print(a*2)

[  2   6  10  14  18  22  26  30  34  38  42  46  50  54  58  62  66  70
  74  78  82  86  90  94  98 102 106 110 114 118 122 126 130 134 138 142
 146 150 154 158 162 166 170 174 178 182 186 190 194 198]


In [93]:
print(a/2)

[ 0.5  1.5  2.5  3.5  4.5  5.5  6.5  7.5  8.5  9.5 10.5 11.5 12.5 13.5
 14.5 15.5 16.5 17.5 18.5 19.5 20.5 21.5 22.5 23.5 24.5 25.5 26.5 27.5
 28.5 29.5 30.5 31.5 32.5 33.5 34.5 35.5 36.5 37.5 38.5 39.5 40.5 41.5
 42.5 43.5 44.5 45.5 46.5 47.5 48.5 49.5]


In [94]:
print(a)

[ 1  3  5  7  9 11 13 15 17 19 21 23 25 27 29 31 33 35 37 39 41 43 45 47
 49 51 53 55 57 59 61 63 65 67 69 71 73 75 77 79 81 83 85 87 89 91 93 95
 97 99]


##### 2D ARRAY

In [95]:
print(arr)

[[   45    78    85     1    12    87]
 [   12    87    68    45     6     5]
 [    7     8     9   100 10000    10]]


In [96]:
print(arr+100)

[[  145   178   185   101   112   187]
 [  112   187   168   145   106   105]
 [  107   108   109   200 10100   110]]


In [97]:
print(arr-21)

[[  24   57   64  -20   -9   66]
 [  -9   66   47   24  -15  -16]
 [ -14  -13  -12   79 9979  -11]]


In [98]:
print(arr*10000)

[[   450000    780000    850000     10000    120000    870000]
 [   120000    870000    680000    450000     60000     50000]
 [    70000     80000     90000   1000000 100000000    100000]]


In [99]:
print(arr//2)

[[  22   39   42    0    6   43]
 [   6   43   34   22    3    2]
 [   3    4    4   50 5000    5]]


#### Array with Array

* Corresponding elements of array will add

In [100]:
b = np.arange(1,51)
print(a+b)

[  2   5   8  11  14  17  20  23  26  29  32  35  38  41  44  47  50  53
  56  59  62  65  68  71  74  77  80  83  86  89  92  95  98 101 104 107
 110 113 116 119 122 125 128 131 134 137 140 143 146 149]


In [101]:
print(a-b)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47
 48 49]


In [102]:
print(a*b)

[   1    6   15   28   45   66   91  120  153  190  231  276  325  378
  435  496  561  630  703  780  861  946 1035 1128 1225 1326 1431 1540
 1653 1770 1891 2016 2145 2278 2415 2556 2701 2850 3003 3160 3321 3486
 3655 3828 4005 4186 4371 4560 4753 4950]


In [103]:
print(b-a)

[  0  -1  -2  -3  -4  -5  -6  -7  -8  -9 -10 -11 -12 -13 -14 -15 -16 -17
 -18 -19 -20 -21 -22 -23 -24 -25 -26 -27 -28 -29 -30 -31 -32 -33 -34 -35
 -36 -37 -38 -39 -40 -41 -42 -43 -44 -45 -46 -47 -48 -49]


* If number of elements are not same then there will be error

In [104]:
print(a)


[ 1  3  5  7  9 11 13 15 17 19 21 23 25 27 29 31 33 35 37 39 41 43 45 47
 49 51 53 55 57 59 61 63 65 67 69 71 73 75 77 79 81 83 85 87 89 91 93 95
 97 99]


In [105]:
print(arr)

[[   45    78    85     1    12    87]
 [   12    87    68    45     6     5]
 [    7     8     9   100 10000    10]]


In [106]:
print(a+arr)

ValueError: operands could not be broadcast together with shapes (50,) (3,6) 

* The arithimatic operation should be always between same datatypes, if datatypes are different, then there will be error

In [ ]:
x = np.full(5,"Rishu")
print(x)

['Rishu' 'Rishu' 'Rishu' 'Rishu' 'Rishu']


In [ ]:
y = np.full(5,1)
print(y)

[1 1 1 1 1]


In [ ]:
print(x+y)

UFuncTypeError: ufunc 'add' did not contain a loop with signature matching types (dtype('<U5'), dtype('int64')) -> None

In [ ]:
print(x+1)

UFuncTypeError: ufunc 'add' did not contain a loop with signature matching types (dtype('<U5'), dtype('int64')) -> None

In [ ]:
print(x + "ABC")

['RishuABC' 'RishuABC' 'RishuABC' 'RishuABC' 'RishuABC']


### MISSING VALUES OR EMPTY VALUES

* None ---> Keyword for empty data in python.
* nan (np.nan) ---> It represents empty data in numpy --> dtype = np.float64

#### nan operations

In [ ]:
x = np.array([2,4,None,None,5])
print(x)

[2 4 None None 5]


In [ ]:
y = np.array([1,3,np.nan,7,np.nan])
print(y)

[ 1.  3. nan  7. nan]


In [ ]:
print(x[0])

2


In [ ]:
print(x[2])

None


In [ ]:
print(x[3])

None


In [ ]:
print(y[0])

1.0


In [ ]:
print(y[2])

nan


In [ ]:
print(x+10) 

TypeError: unsupported operand type(s) for +: 'NoneType' and 'int'

In [ ]:
print(y+10)

[11. 13. nan 17. nan]


* None doesn't allow us to do any form of operation in the array
* Whereas np.nan allows us to do array operations even we've a missing data in the array, while performing operation, it simply gives nan where a nan value is being operated

### RANDOM MODULE IN NUMPY

#### np.random.randint()

* Syntax --> np.random.randint(low,high = None, size = None)
* high is not included
* low is included
* If only low is passed; it gives a random number between 0 and low
* Size is the amount of numbers to generate (or shape of array)

In [ ]:
#GENERATING A SINGLE NUMBER
print(np.random.randint(1,10))

7


In [ ]:
#GENERATING AN ARRAY OF 5 RANDOM NUMBERS
print(np.random.randint(1,10,5))

[5 6 6 6 9]


In [ ]:
#GENERATING AN ARRAY OF 10 RANDOM NUMBERS
print(np.random.randint(1,100,5))

[45 43 95 33 79]


In [ ]:
#GENERATING A 2*3 MATRIX (2 rows and 3 columns)
print(np.random.randint(1,100,size = (2,3)))

[[16 11 44]
 [42 40 94]]


In [ ]:
#GENERATING A 4*5 MATRIX (4 rows and 5 columns)
print(np.random.randint(1,100,(4,5)))

[[42 62 30 54 71]
 [84 40 63 44  7]
 [63 56 88  2 26]
 [80 19 11 73 83]]


#### seed()

* Seed is a function which gives the same random data for a prescribed value & size

In [ ]:
np.random.seed(31)
x = np.random.randint(1,100,20)
print(x)

[83 88 17 99 24 59 29 94 93 43 47  7 83 19 26 82 24 29 11 85]


In [ ]:
np.random.seed(31)
y = np.random.randint(1,100,20)
print(y)

[83 88 17 99 24 59 29 94 93 43 47  7 83 19 26 82 24 29 11 85]


### STACKING ARRAYS

In [ ]:
import numpy as np
a = np.random.randint(1,100,size = (2,3))
b = np.random.randint(1,100,size = (2,3))
print(a)

[[49 76 53]
 [44 65 16]]


In [ ]:
print(b)

[[16 71 41]
 [55 13 12]]


* There are two types of stacking.
    * HORIZONTAL STACK
        * hstack
        * arrays will join one after other (column stacking)
        * for horizontal stacking number of rows should remain same
    * VERTICAL STACK 
        * vstack 
        * arrays will join below one other 
        * for vertical stacking columns should remain same

In [ ]:
print(a)
print()
print(b)
print()
print(np.hstack((a,b))) # ROWS ARE SAME

[[49 76 53]
 [44 65 16]]

[[16 71 41]
 [55 13 12]]

[[49 76 53 16 71 41]
 [44 65 16 55 13 12]]


In [ ]:
a = np.random.randint(1,100,size = (4,3))
b = np.random.randint(1,100,size = (2,3))
print(a)
print()
print(b)

[[68 83 48]
 [88 93  3]
 [96 40 63]
 [65 61 36]]

[[56 36 23]
 [23 12 33]]


In [ ]:
np.hstack((a,b)) # ROWS ARE NOT SAME, SO IT WILL THROW AN ERROR

ValueError: all the input array dimensions except for the concatenation axis must match exactly, but along dimension 0, the array at index 0 has size 4 and the array at index 1 has size 2

In [ ]:
np.vstack((a,b)) # COLUMNS ARE SAME, SO IT WILL WORK FINE

array([[68, 83, 48],
       [88, 93,  3],
       [96, 40, 63],
       [65, 61, 36],
       [56, 36, 23],
       [23, 12, 33]])

In [ ]:
a = np.random.randint(1,100,size = (2,3))
b = np.random.randint(1,100,size = (2,4))
print(a)
print()
print(b)
print()
print(np.vstack((a,b))) # COLUMNS ARE NOT SAME, SO IT WILL THROW AN ERROR

[[23 66 23]
 [22 78  6]]

[[83 68 79 26]
 [98 52 10  1]]



ValueError: all the input array dimensions except for the concatenation axis must match exactly, but along dimension 1, the array at index 0 has size 3 and the array at index 1 has size 4

* We can also perform the same operation using np.stack()
* SYNTAX:
        np.stack((a,b),axis = (0/1)) 

### TILE & REPEAT

* Tile is a process in which we repeat the whole 2D array

In [ ]:
a = np.random.randint(1,100,size = (2,3))
print(a)


[[90 47 67]
 [21 78 26]]


In [ ]:
np.tile(a,4)

array([[90, 47, 67, 90, 47, 67, 90, 47, 67, 90, 47, 67],
       [21, 78, 26, 21, 78, 26, 21, 78, 26, 21, 78, 26]])

In [ ]:
np.tile(a,(3,4))

array([[90, 47, 67, 90, 47, 67, 90, 47, 67, 90, 47, 67],
       [21, 78, 26, 21, 78, 26, 21, 78, 26, 21, 78, 26],
       [90, 47, 67, 90, 47, 67, 90, 47, 67, 90, 47, 67],
       [21, 78, 26, 21, 78, 26, 21, 78, 26, 21, 78, 26],
       [90, 47, 67, 90, 47, 67, 90, 47, 67, 90, 47, 67],
       [21, 78, 26, 21, 78, 26, 21, 78, 26, 21, 78, 26]])

* In Repeat() the elements of the array are repeated
* Shape will always be 1D

In [ ]:
np.repeat(a,4)

array([90, 90, 90, 90, 47, 47, 47, 47, 67, 67, 67, 67, 21, 21, 21, 21, 78,
       78, 78, 78, 26, 26, 26, 26])

In [ ]:
np.repeat(a,(3,4))

ValueError: operands could not be broadcast together with shape (6,) (2,)

In [ ]:
np.repeat(a,4,axis = 0) # REPEATS THE ROWS

array([[90, 47, 67],
       [90, 47, 67],
       [90, 47, 67],
       [90, 47, 67],
       [21, 78, 26],
       [21, 78, 26],
       [21, 78, 26],
       [21, 78, 26]])

In [ ]:
np.repeat(a,4,axis = 1) # REPEATS THE COLUMNS # THIS IS BYDEFAULT

array([[90, 90, 90, 90, 47, 47, 47, 47, 67, 67, 67, 67],
       [21, 21, 21, 21, 78, 78, 78, 78, 26, 26, 26, 26]])

### RESHAPE()

In [ ]:
import numpy as np
a = np.random.randint(1,100,12)
print(a)

[48 55 51 81  8  6 74 67 15 70 96 23]


In [ ]:
a.shape

(12,)

In [ ]:
a.ndim

1

In [ ]:
a.reshape((3,4))

array([[48, 55, 51, 81],
       [ 8,  6, 74, 67],
       [15, 70, 96, 23]])

In [ ]:
a.reshape((2,6))

array([[48, 55, 51, 81,  8,  6],
       [74, 67, 15, 70, 96, 23]])

In [ ]:
a.reshape((1,12))

array([[48, 55, 51, 81,  8,  6, 74, 67, 15, 70, 96, 23]])

In [ ]:
a.reshape((12,1))

array([[48],
       [55],
       [51],
       [81],
       [ 8],
       [ 6],
       [74],
       [67],
       [15],
       [70],
       [96],
       [23]])

In [ ]:
a = np.random.randint(1,100,(5,2))
print(a)

[[ 3 24]
 [13  8]
 [52 35]
 [29 87]
 [53 63]]


In [ ]:
a.reshape(10)

array([ 3, 24, 13,  8, 52, 35, 29, 87, 53, 63])

* Create a 2D array of 10 even numbers of order 5X2

In [ ]:
a = np.arange(2,21,2)
a.reshape((5,2))


array([[ 2,  4],
       [ 6,  8],
       [10, 12],
       [14, 16],
       [18, 20]])

In [ ]:
a = np.arange(2,21,2).reshape((5,2))
a

array([[ 2,  4],
       [ 6,  8],
       [10, 12],
       [14, 16],
       [18, 20]])

### where()

* It is used for data transformation
* It is used for data encoding ()

In [107]:
marks = np.random.randint(1,100,5,dtype = np.int64)
print(marks)

[28 52 60 18 33]


In [108]:
np.where(marks>50,"Pass","Fail")

array(['Fail', 'Pass', 'Pass', 'Fail', 'Fail'], dtype='<U4')

In [109]:
result = np.where(marks > 50,"Pass","Fail")
print(result)

['Fail' 'Pass' 'Pass' 'Fail' 'Fail']


### SELECT()

* It is used when we want to assign data by considering variouse conditions.
* IF-ELIF-ELSE wala hisaab

In [115]:
grade = np.select(
    [marks >= 90, marks >= 75, marks >= 50, marks >= 33, marks < 33],
    ["A", "B", "C", "D", "F"],
    default="F"
)
grade

array(['F', 'C', 'C', 'F', 'D'], dtype='<U1')