In [2]:
import numpy as np
np.random.seed(3)
marks=np.random.randint(1,101,size=(3,4))
print(marks)


[[25  4 57 73]
 [ 1 22 20 75]
 [42 11 22 39]]


In [1]:
import numpy as np
a = np.array([2,3,4,5,6])
print(a.shape)

(5,)


In [2]:
import numpy as np
np.random.seed(3)
marks=np.random.randint(1,101,size=(3,4))
print(marks)


[[25  4 57 73]
 [ 1 22 20 75]
 [42 11 22 39]]


In [4]:
import numpy as np
np.random.seed(4)
marks=np.random.randint(1,101,size=(3,4))
print(marks)


[[47 56 70  2]
 [88 73 51 10]
 [59 95 56 56]]


In [5]:
marks[1:,1:]=5
print(marks)

[[47 56 70  2]
 [88  5  5  5]
 [59  5  5  5]]


In [15]:
import numpy as np
a = np.random.randint(1,100,(3,4))
print(a)

[[81 40 54 23]
 [48  1 46 25]
 [78 73 49  3]]


In [16]:
print(a[1:3,1:4])

[[ 1 46 25]
 [73 49  3]]


In [21]:
print(a[0:3,[1,2]])

[[40 54]
 [ 1 46]
 [73 49]]
